

#_______________________________________________________________________________


make_prediction_map <- function(A_matrix, P_vector,remove_obs=F){
  
  # Use this function to create a dataframe containing INLA predictions with their locations.
  
  # A_matrix = Locp, a matrix of locations (x and y) specified in the INLA model
  # P_vector = p.pred, a vector containing the predictions generated by INLA
  # if remove_obs=T, the 'observation' column will be removed from the final df (useful for merging)
  
  library(dplyr)
  
  A_df <- as.data.frame(A_matrix*1000)
  A_df$observation <- 1:nrow(A_df) 
  colnames(A_df)[1:2]<-c("xm","ym")
  
  P_df <- as.data.frame(P_vector)
  colnames(P_df)<-c(substitute(P_vector))
  P_df$observation <- 1:nrow(P_df) 
  
  
  df_full <- merge(A_df,P_df,by="observation")
  
  if(remove_obs == T){
    df_full <- df_full[,2:4]}
  
  return(df_full)
  
}

#_______________________________________________________________________________

append_prediction_map <- function(Existing_df, P_vector,remove_obs=F){
  

  # Use this function to append a vector onto an existing df with the same number of rows.
  # Ideally used to append additional INLA predictions to existing prediction df 
  # for example, to add in predictions based on different climactic scenarios OR
  # to combine the predictive outputs of different model formulations 
  # The x and y matrix must be the same
  
  # A_matrix = Locp, a matrix of locations (x and y)
  # P_vector = p.pred, a vector containing the predictions generated by INLA
  # if remove_obs=T, the 'observation' column will be removed from the final df (useful for merging)
  
   library(dplyr) 
  P_df <- as.data.frame(P_vector)
  colnames(P_df)<-c(substitute(P_vector))
  P_df$observation <- 1:nrow(P_df) 
  
  if(!"observation" %in% colnames(Existing_df))
  {
    Existing_df$observation <- 1:nrow(Existing_df) 
  }
  
  df_full <- merge(Existing_df,P_df,by="observation")
  
  if(remove_obs == T){
    df_full <- df_full[,-1]}
  
  return(df_full) 
}

#_______________________________________________________________________________

# Shoot hole in polygon (spdf) using another polygon (spdf)
# https://stackoverflow.com/questions/29624895/how-to-add-a-hole-to-a-polygon-within-a-spatialpolygonsdataframe

library("sp")
AddHoleToPolygon <-function(poly,hole){
  # invert the coordinates for Polygons to flag it as a hole
  coordsHole <-  hole@polygons[[1]]@Polygons[[1]]@coords
  newHole <- Polygon(coordsHole,hole=TRUE)
  
  # punch the hole in the main poly
  listPol <- poly@polygons[[1]]@Polygons
  listPol[[length(listPol)+1]] <- newHole
  punch <- Polygons(listPol,poly@polygons[[1]]@ID)
  
  # make the polygon a SpatialPolygonsDataFrame as the entry
  new <- SpatialPolygons(list(punch),proj4string=poly@proj4string)
  new <- SpatialPolygonsDataFrame(new,data=as(poly,"data.frame"))
  
  return(new)
}

